/* ============================================
   MAIN.JS
   Generated by Smooth Builder Pro v3.0
   ============================================ */

(function() {
  'use strict';

  // ============================================
  // MOBILE MENU
  // ============================================
  
  const menuToggle = document.getElementById('menu-toggle');
  const mobileNav = document.getElementById('mobile-nav');
  const body = document.body;
  
  if (menuToggle && mobileNav) {
    menuToggle.addEventListener('click', function() {
      const isOpen = menuToggle.classList.toggle('open');
      mobileNav.classList.toggle('open');
      menuToggle.setAttribute('aria-expanded', isOpen);
      mobileNav.setAttribute('aria-hidden', !isOpen);
      
      // Prevent body scroll when menu is open
      body.style.overflow = isOpen ? 'hidden' : '';
    });
    
    // Close menu on link click
    mobileNav.querySelectorAll('a').forEach(function(link) {
      link.addEventListener('click', function() {
        menuToggle.classList.remove('open');
        mobileNav.classList.remove('open');
        menuToggle.setAttribute('aria-expanded', 'false');
        mobileNav.setAttribute('aria-hidden', 'true');
        body.style.overflow = '';
      });
    });
    
    // Close menu on Escape
    document.addEventListener('keydown', function(e) {
      if (e.key === 'Escape' && mobileNav.classList.contains('open')) {
        menuToggle.click();
      }
    });
  }

  // ============================================
  // SMOOTH SCROLL
  // ============================================
  
  document.querySelectorAll('a[href^="#"]').forEach(function(anchor) {
    anchor.addEventListener('click', function(e) {
      const targetId = this.getAttribute('href');
      if (targetId === '#') return;
      
      const target = document.querySelector(targetId);
      if (target) {
        e.preventDefault();
        const headerHeight = document.querySelector('.header')?.offsetHeight || 0;
        const targetPosition = target.getBoundingClientRect().top + window.pageYOffset - headerHeight - 20;
        
        window.scrollTo({
          top: targetPosition,
          behavior: 'smooth'
        });
      }
    });
  });

  // ============================================
  // HEADER SCROLL EFFECT
  // ============================================
  
  const header = document.querySelector('.header');
  
  if (header) {
    let lastScroll = 0;
    
    window.addEventListener('scroll', function() {
      const currentScroll = window.pageYOffset;
      
      if (currentScroll > 50) {
        header.classList.add('scrolled');
      } else {
        header.classList.remove('scrolled');
      }
      
      lastScroll = currentScroll;
    }, { passive: true });
  }


  // ============================================
  // DARK MODE TOGGLE
  // ============================================
  
  const darkToggle = document.getElementById('dark-toggle');
  const html = document.documentElement;
  
  // Check saved preference or system preference
  function getPreferredTheme() {
    const saved = localStorage.getItem('theme');
    if (saved) return saved;
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
  }
  
  // Apply theme
  function applyTheme(theme) {
    if (theme === 'dark') {
      html.classList.add('dark');
      body.classList.add('dark');
      if (darkToggle) darkToggle.textContent = '☀️';
    } else {
      html.classList.remove('dark');
      body.classList.remove('dark');
      if (darkToggle) darkToggle.textContent = '🌙';
    }
    localStorage.setItem('theme', theme);
  }
  
  // Initialize
  applyTheme(getPreferredTheme());
  
  // Toggle handler
  if (darkToggle) {
    darkToggle.addEventListener('click', function() {
      const current = html.classList.contains('dark') ? 'dark' : 'light';
      applyTheme(current === 'dark' ? 'light' : 'dark');
    });
  }
  
  // Listen for system preference changes
  window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', function(e) {
    if (!localStorage.getItem('theme')) {
      applyTheme(e.matches ? 'dark' : 'light');
    }
  });



  // ============================================
  // COOKIE BANNER
  // ============================================
  
  const cookieBanner = document.getElementById('cookie-banner');
  const cookieAccept = document.getElementById('cookie-accept');
  const cookieNecessary = document.getElementById('cookie-necessary');
  
  // Check if consent was already given
  function hasConsent() {
    return localStorage.getItem('cookie-consent') !== null;
  }
  
  // Hide banner
  function hideBanner() {
    if (cookieBanner) {
      cookieBanner.classList.add('hidden');
    }
  }
  
  // Save consent
  function saveConsent(type) {
    localStorage.setItem('cookie-consent', type);
    localStorage.setItem('cookie-consent-date', new Date().toISOString());
    hideBanner();
  }
  
  // Initialize
  if (hasConsent()) {
    hideBanner();
  }
  
  // Event handlers
  if (cookieAccept) {
    cookieAccept.addEventListener('click', function() {
      saveConsent('all');
    });
  }
  
  if (cookieNecessary) {
    cookieNecessary.addEventListener('click', function() {
      saveConsent('necessary');
    });
  }


  // ============================================
  // INTERSECTION OBSERVER (Fade-in animations)
  // ============================================
  
  if ('IntersectionObserver' in window) {
    const fadeElements = document.querySelectorAll('.service-card, .testimonial, .team-member, .benefit');
    
    const fadeObserver = new IntersectionObserver(function(entries) {
      entries.forEach(function(entry) {
        if (entry.isIntersecting) {
          entry.target.style.opacity = '1';
          entry.target.style.transform = 'translateY(0)';
          fadeObserver.unobserve(entry.target);
        }
      });
    }, {
      threshold: 0.1,
      rootMargin: '0px 0px -50px 0px'
    });
    
    fadeElements.forEach(function(el) {
      el.style.opacity = '0';
      el.style.transform = 'translateY(20px)';
      el.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
      fadeObserver.observe(el);
    });
  }

  // ============================================
  // FOCUS VISIBLE POLYFILL (for older browsers)
  // ============================================
  
  document.addEventListener('keydown', function(e) {
    if (e.key === 'Tab') {
      document.body.classList.add('keyboard-nav');
    }
  });
  
  document.addEventListener('mousedown', function() {
    document.body.classList.remove('keyboard-nav');
  });

})();
